language: node_js
node_js:
  - 8
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run brain-store
after_success: 
  - npm run brain-store:coverall

branches:
  only:
    - main